version: "3"

services:

    app:
        build: .
        ports:
            - 3000:3000
        volumes:
            - ./node_modules/:/app/node_modules/
            - ./src/:/app/src
            - ./logs/:/app/logs
        container_name: application_challenge_e